#!/bin/bash
################################################################################
## se7endb.sh <flag>                                                          ##
## A bash script for mounting/unmounting the following SevenDB remote         ##
## directories (hosted on pi7db) using sshfs / fusermount:                    ##
##  -- pi7db:/home/sevendb/FILMS001                                           ##
##  -- pi7db:/home/sevendb-plus/FILMS002                                      ##
##  --+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ##
##                                                                            ##
## Usage: se7endb [options]                                                   ##
## Options:                                                                   ##
##    -r <remote>          : set the remote that hosts SevenDB                ##
##    -m <mount_point>     : set directory where remote sevendb will be       ##
##                           mounted on                                       ##
##    <flag>               : set either to "on", for mounting remote sevendb  ##
##                           direcotry using sshff, "off" for unmounting it   ##
##                           using fusermount, or leave it empty for getting  ##
##                           the status of mount point                        ##
##                                                                            ##
################################################################################

b=$(tput bold)
n=$(tput sgr0)
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

# Help function
help(){
    echo "${b}Usage:${n} se7endb.sh [-m <mount_point>] <flag>" 1>&2; exit 1;
}

# Initialize variables
OPTIND=1
SEVENDB_MOUNT_POINT=~/SEVENDB

# Parse command line arguments
while getopts ":m:" options
do
    case $options in
        m ) SEVENDB_MOUNT_POINT="$OPTARG"
            ;;
        * ) help
            ;;
    esac
done
shift $(expr $OPTIND - 1 )

if [[ $# -gt 0 ]]; then
    # A flag has been given
    flag=$1
    if [[ "${flag}" == "on" ]]; then
        echo "Mount SEVENDB..."
        mkdir -p $SEVENDB_MOUNT_POINT
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS001
        sshfs -o idmap=user plex-sdb:/home/sevendb/films/films1/FILMS001 $SEVENDB_MOUNT_POINT/FILMS001
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS002
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films2/FILMS002 $SEVENDB_MOUNT_POINT/FILMS002
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS003
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films3/FILMS003 $SEVENDB_MOUNT_POINT/FILMS003
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS004
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films4/FILMS004 $SEVENDB_MOUNT_POINT/FILMS004
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS005
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films5/FILMS005 $SEVENDB_MOUNT_POINT/FILMS005
        mkdir -p $SEVENDB_MOUNT_POINT/FILMS006
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films6/FILMS006 $SEVENDB_MOUNT_POINT/FILMS006
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS007
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films7/FILMS007 $SEVENDB_MOUNT_POINT/FILMS007
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS008
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films8/FILMS008 $SEVENDB_MOUNT_POINT/FILMS008
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS009
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films9/FILMS009 $SEVENDB_MOUNT_POINT/FILMS009
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS010
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films10/FILMS010 $SEVENDB_MOUNT_POINT/FILMS010
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS011
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films11/FILMS011 $SEVENDB_MOUNT_POINT/FILMS011
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS012
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films12/FILMS012 $SEVENDB_MOUNT_POINT/FILMS012
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS013
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films13/FILMS013 $SEVENDB_MOUNT_POINT/FILMS013
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS014
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films14/FILMS014 $SEVENDB_MOUNT_POINT/FILMS014
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS015
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films15/FILMS015 $SEVENDB_MOUNT_POINT/FILMS015
	mkdir -p $SEVENDB_MOUNT_POINT/FILMS016
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/films/films16/FILMS016 $SEVENDB_MOUNT_POINT/FILMS016
	# ---
	mkdir -p $SEVENDB_MOUNT_POINT/SERIES001
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/series/series1/SERIES001 $SEVENDB_MOUNT_POINT/SERIES001
	mkdir -p $SEVENDB_MOUNT_POINT/SERIES002
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/series/series2/SERIES002 $SEVENDB_MOUNT_POINT/SERIES002
	mkdir -p $SEVENDB_MOUNT_POINT/SERIES003
        sshfs -o idmap=user,gid=1002 plex-sdb:/home/sevendb/series/series3/SERIES003 $SEVENDB_MOUNT_POINT/SERIES003
	
    elif [[ "${flag}" == "off" ]]; then
        echo "Unmount SEVENDB..."
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS001
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS002
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS003
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS004
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS005
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS006
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS007
        fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS008
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS009
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS010
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS011
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS012
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS013
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS014
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS015
	fusermount3 -u $SEVENDB_MOUNT_POINT/FILMS016
	# ---
	fusermount3 -u $SEVENDB_MOUNT_POINT/SERIES001
	fusermount3 -u $SEVENDB_MOUNT_POINT/SERIES002
	fusermount3 -u $SEVENDB_MOUNT_POINT/SERIES003
    else
        echo "${b}${red}[Invalid flag]${reset}${n} Choose:"
        echo " -- ${b}${red}on${reset}${n} (to mount SEVENDB on $SEVENDB_MOUNT_POINT),"
        echo " -- ${b}${red}off${reset}${n} (to unmount SEVENDB from $SEVENDB_MOUNT_POINT), or "
        echo " -- leave it ${b}${red}empty${reset}${n} for getting current status"
    fi

else
    # No flag has been given -- print status
    # --- FILMS001 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS001 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS001 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS001${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS001
    else
        echo "SEVENDB/FILMS001 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS001${reset}${n}"
    fi
    # --- FILMS002 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS002 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS002 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS002${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS002
    else
        echo "SEVENDB/FILMS002 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS002${reset}${n}"
    fi
    # --- FILMS003 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS003 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS003 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS003${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS003
    else
        echo "SEVENDB/FILMS003 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS003${reset}${n}"
    fi
    # --- FILMS004 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS004 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS004 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS004${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS004
    else
        echo "SEVENDB/FILMS004 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS004${reset}${n}"
    fi
    # --- FILMS005 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS005 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS005 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS005${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS005
    else
        echo "SEVENDB/FILMS005 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS005${reset}${n}"
    fi
    # --- FILMS006 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS006 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS006 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS006${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS006
    else
        echo "SEVENDB/FILMS006 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS006${reset}${n}"
    fi
    # --- FILMS007 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS007 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS007 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS007${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS007
    else
        echo "SEVENDB/FILMS007 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS007${reset}${n}"
    fi
    # --- FILMS008 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS008 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS008 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS008${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS008
    else
        echo "SEVENDB/FILMS008 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS008${reset}${n}"
    fi
    # --- FILMS009 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS009 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS009 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS009${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS009
    else
        echo "SEVENDB/FILMS009 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS009${reset}${n}"
    fi
    # --- FILMS010 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS010 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS010 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS010${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS010
    else
        echo "SEVENDB/FILMS010 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS010${reset}${n}"
    fi
    # --- FILMS011 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS011 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS011 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS011${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS011
    else
        echo "SEVENDB/FILMS011 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS011${reset}${n}"
    fi
    # --- FILMS012 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS012 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS012 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS012${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS012
    else
        echo "SEVENDB/FILMS012 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS012${reset}${n}"
    fi
    # --- FILMS013 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS013 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS013 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS013${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS013
    else
        echo "SEVENDB/FILMS013 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS013${reset}${n}"
    fi
    # --- FILMS014 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS014 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS014 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS014${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS014
    else
        echo "SEVENDB/FILMS014 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS014${reset}${n}"
    fi
    # --- FILMS015 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS015 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS015 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS015${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS015
    else
        echo "SEVENDB/FILMS015 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS015${reset}${n}"
    fi
    # --- FILMS016 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/FILMS016 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/FILMS016 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS016${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/FILMS016
    else
        echo "SEVENDB/FILMS016 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/FILMS016${reset}${n}"
    fi
    
    # --- SERIES001 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/SERIES001 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/SERIES001 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES001${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/SERIES001
    else
        echo "SEVENDB/SERIES001 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES001${reset}${n}"
    fi
    # --- SERIES002 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/SERIES002 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/SERIES002 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES002${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/SERIES002
    else
        echo "SEVENDB/SERIES002 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES002${reset}${n}"
    fi
    # --- SERIES003 ---
    mountpoint -q $SEVENDB_MOUNT_POINT/SERIES003 >> /dev/null
    status=$?
    if [[ $status -eq 0 ]]; then
        echo "SEVENDB/SERIES003 is mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES003${reset}${n}"
        lsof -w $SEVENDB_MOUNT_POINT/SERIES003
    else
        echo "SEVENDB/SERIES003 is ${b}${red}not${reset}${n} mounted on ${b}${red}$SEVENDB_MOUNT_POINT/SERIES003${reset}${n}"
    fi
fi
